#ifndef ScriptSourceH
#define ScriptSourceH

enum ScriptSource {
	SCRIPT_SRC_TYPE_SCRIPT_WINDOW = 0,
	SCRIPT_SRC_TYPE_ON_FILE_SAVED,
	SCRIPT_SRC_TYPE_ON_FILE_OPENED,
	SCRIPT_SRC_TYPE_ON_HOTKEY,
	SCRIPT_SRC_TYPE_ON_STARTUP,
	SCRIPT_SRC_TYPE_ON_TIMER,

	SCRIPT_SRC_TYPE_LIMITER
};

#endif
